### ISSUE TITLE
the dll is locked if run copy-extensions again.

### ISSUE THREAD

**Issue by Anson99** [DmitrySikorsky/AspNet5ModularApp#1]
when the dll is loaded, if you run gulp task 'copy-extensions' again, there is a error, the dll is locked.

**Comment by DmitrySikorsky** [comment]
Just stop your web server (it is IIS express I think) and then run the task. It is normal that dlls are locked while the application is running I think.

**Comment by Anson99** [comment]
That is not so convenient, it is better if it can unload and reload dll.

**Comment by DmitrySikorsky** [comment]
It can be done in code with some UI, but this is not the main point of this sample. (Gulp task is only to simplify files copying, you will not use it in 'real life', you will have some UI instead or just copy libs manually.)
